global:
  slack_api_url: "https://hooks.slack.com/services/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"

route:
  group_by: ['instance']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver: slack-notifications

  routes:
  - match:
      severity: critical
    receiver: slack-notifications

receivers:
  - name: slack-notifications
    slack_configs:
      - channel: '#prometheus'
        send_resolved: true
        username: prometheus
