global:
  slack_api_url: "https://hooks.slack.com/services/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"
  smtp_smarthost: 'smtp.amegaserver.com:25'
  smtp_from: 'test@amegaserver.com'
  smtp_auth_username: 'test@amegaserver.com'
  smtp_auth_password: 'Y9o5Q3n8'

route:
  group_by: ['instance']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver:
    - slack-notifications
    - email

  routes:
  - match:
      severity: critical
    receiver:
      - slack-notifications
      - email

receivers:
  - name: slack-notifications
    slack_configs:
      - channel: '#prometheus'
        send_resolved: true
        username: prometheus
  - name: email
    email_configs:
      - to: 'test@amegaserver.com'
