kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: fB/ioe2Guhy2SsX9j+2F+qASqx9uqfa+zzTQEKzmAAc=
      - identity: {}
